= „Route wird neu berechnet“ (Lesezeit: ca. 8 Minuten)

Verpasst. Typisch. Früher hatte Paul oft die einzige Bushaltestelle von Seligenburg verpennt, heute eben die Ausfahrt. Er hatte sich darauf verlassen, dass die Schlaglöcher auf den letzten Kilometern ihn auch dieses Mal pünktlich aus seinen Autopilot-Gedanken reißen würden. Offenbar war die Straße aber seit seinem letzten Besuch ausgebessert worden, nach Jahrzehnten. Konnte doch keiner ahnen, obwohl ein Klassiker: Leicht geänderte Umweltbedingungen und schon laufen lang bewährte Coping-Strategien ins Leere. Wenn man es dann merkt, ist es oft schon zu spät.

„Die Route wird neu berechnet.“ Dann folgte ein strenges „Bitte wenden!“ Das Navi hatte 20 Minuten zur Ankunftszeit addiert, Pauls Herz deshalb gefühlt 20 Schläge mehr pro Minute und sein innerer Kritiker eine XL-Portion Selbstanklage. Fehlte nur noch, dass die Motorkontroll-Leuchte wieder anging, wie zuletzt häufig auf längeren Strecken. Die Werkstatt hatte nach mehreren Diagnose-Versuchen aufgegeben. („Wohl ein alter Fehler im System, der nicht richtig gelöscht werden kann, Herr Krampitz. Wir können das Problem im Moment nicht reproduzieren. Beobachten Sie das doch einfach und kommen Sie rein, wenn es wieder passiert.“)

Paul hatte sich vorgenommen, diesen Wortlaut für seine Sprechstunde auswendig zu lernen, nur ohne das invalidierend-dämliche „einfach“ vielleicht. Die Einschätzung klang doch immerhin kompetenter und vertrauensbildender als „Ich habe ehrlicherweise keine Ahnung, was Ihnen fehlt! Die Forschung ist noch nicht so weit. Von der Funktionsweise unserer Synapsen und vieler Medikamente wissen wir noch weniger als vom Steuerungssystem Ihres Fahrzeugs.“

„Bitte wenden!“ hörte Paul erneut. Damit auch seine eigene Stimme klang wie der Erwachsene, der er seit über 25 Jahren war und als der er hier in dieser Geschichte jetzt am Steuer sitzen sollte, musste er jetzt aber erstmal sein eigenes Navi sein: „Ganz ruhig, Paul. Das alles stand so nicht auf dem Plan. Ist aber ok. Krise kannst Du. Mach weiter, so gut es eben geht.“ Ein paar Atemzüge, nicht zu tief in den Bauch, eher flach. Von eins bis fünf einatmen wie durch einen Strohhalm, Atempause, dann von fünf bis eins wieder aus, mit Lippenbremse. Wieder von vorn. 1, 2, 3, 4 …

OK. Jetzt bei den Kindern anrufen. Sie warteten bestimmt schon. „Hallo, Leni. Happy Birthday, trotz allem. Ich komme gerade von bei Eurer Mutter, ja. Sie ist schon wieder wach. Schickt liebe Grüße. Ich bin gleich bei Euch. So gegen halb 6. Oder soll ich noch was einkaufen?“ Als er sich gerade nach ihren Geschwistern erkundigen wollte, hatte seine Nichte schon mit einem „Bis gleich dann“ aufgelegt, und Paul war wieder allein mit den nörgelnden Stimmen des Navis und des Inneren Kritikers.

„Bitte wenden!“ Was machte er hier, mitten im Nirgendwo? Vieles hatte er inzwischen etwas besser im Griff in seinem eigenen kleinen Leben, ja. Nach Jahren des Trainings. Trotzdem bekam er oft nicht mal auf die Reihe, seinen privaten Briefkasten regelmäßig zu leeren. Dringender Papierkram war immer noch zu oft überfällig, ein noch unfertiges Fachbuch-Kapitel sollte schon vorgestern an den Verlag gehen und auch die Steuererklärung war wieder unpünktlich. Und jetzt sollte er hier als rettender Onkel aus der Großstadt aufschlagen?

Notfall ist eben Notfall. Bergauf ging immer schon besser als die Ebene. Auf eine paradoxe Art war Paul sogar erleichtert, aus seinem Alltag flüchten zu können. Nicht ohne sich der ambivalenten Gefühle bewusst zu sein und sich für sie zu schämen, versteht sich. Aber so tickte er eben, und immerhin wusste er inzwischen in der Theorie, warum das so war.

Nur in der Praxis sah es weiterhin etwas anders aus. Da wollte er doch gerade heute extrafrüh und betont rational in den Tag starten, um „jetzt aber wirklich“ Termine und To-do-Listen abzuarbeiten. Als er vormittags dann kurz in der Teeküche stand, hatte völlig unerwartet seine Schwester angerufen. Aus der Notaufnahme der Kleinstadt-Klinik nahe von Seligenburg, zwischen Röntgen und schon absehbarer OP: komplexe Fraktur nach Fahrradsturz.

„Scheiße, Rike. Was ist denn passiert? Hast Du Schmerzen? Soll ich mal mit dem Arzt sprechen?“ Nein, das sei alles im Griff. Er wollte ihr gerade noch einschärfen, die erwartbare Frage nach Vorerkrankungen und Medikamenten ehrlich zu beantworten („Bitte, Rike, kann echt wichtig sein für die Narko….“), aber sie fiel ihm ins Wort: „Darum geht es mir gar nicht. Ich habe nur niemanden für die Kinder, Paul. Ich würde Dich sicher nicht anrufen, wenn ich irgendeine andere Möglichkeit sehen würde.“ Und dann leiser: „Ich kann auch wirklich niemanden ins Haus lassen, sonst… Es sieht leider echt schlimm chaotisch aus gerade. Und ich weiß nicht, ob die Kinder weiter ihre…, wenn …“

Ihre Stimme brach - und Pauls letzte Widerstände gleich mit. Es war ihm leider viel zu vertraut, dass Scham und Alltagsüberforderung als ständige Wegbegleiter selbst in so einer Situation alles dominierten. Wenigstens ihm sollte sie das jetzt nicht erklären müssen.

Und so sagte Paul all das nicht, was sein Energiesparmodus ihm eigentlich zur Abwehr diktierte: „Ich würde ja gern, aber … Kann denn nicht einer der Väter…? Eine Freundin oder Frau Schmied vom Hof nebenan? Hier ist auch alles gerade wieder total unter Wasser. Fristen und… Ende nächster Woche kann ich vielleicht für ein paar Tage kommen?“

Stattdessen nur: „OK.“ „Was, OK? Du kommst?“ fragte seine Schwester. „Danke, Paul. Leni wird sich besonders freuen. Ist ja noch dazu ihr Geburtstag heute. Ausgerechnet heute passiert mir das.“ Die zunehmenden Hintergrundgeräusche signalisierten wachsende Dringlichkeit in der Notaufnahme. Sie musste auflegen, aber wollte noch selbst ihre Familien-Whatsapp-Gruppe informieren, dass und warum die Kinder nach der Schule zu Hause auf ihren „Onkel Paul“ warten sollten.

Der schaltete jetzt übergangslos in den Onkel-Paul-Alarm-Modus, erst innen, dann außen: was jetzt, wie weiter? Am Kühlschrank hing ein Spruch, den seine Assistentin, Frau Meyerling, aus ihrem Tischkalender „365 Tage Achtsamkeit“ gerissen hatte: „Sei du selbst die Veränderung, die du dir wünschst für diese Welt!“ (Mahatma Gandhi)

Er nahm den Zettel ab und legte ihn auf den Empfangstresen vor Frau Meyerling, als sei es ein Verteidigungsschriftsatz seines Anwalts Dr. Gandhi zur Rechtfertigung des gleich überstürzt nötigen Aufbruchs. Das meiste Orga-Schlammassel mit Terminverlegungen und Vertretung würde jetzt zweifellos erstmal an ihr hängen. Das fehlte gerade noch. Es verging ja ohnehin kein Tag, an dem sie Paul nicht grundgenervt seine administrativen Defizite vorhielt. Einmal im Quartal drohte sie mit Kündigung. Aber jetzt war sie seltsam gerührt: die kleine, problembeladene Schwester in der Provinz, alleinerziehend, die armen Kinder, ganz auf sich gestellt. Natürlich musste er, der große Bruder und Patenonkel, jetzt… Ja, das verstand sie, zumindest heute. Sie fühlte sich ein bisschen wie in der ARD-Vorabendserie, die sie bei den Besuchen im Pflegeheim oft mit ihrer Mutter sah. Derart beflügelt machte sie sich ans Werk . Paul fuhr nach Hause, packte ein paar Sachen und startete dann die mehrstündige Fahrt nach Seligenburg, inklusive Zwischenstopp im Krankenhaus.

Die Oberärztin, die Rike operiert hatte, berichtete, dass vor allem Kreislauf und Nervensystem ihr Sorgen machen würden. Der Bruch war gerichtet und würde wieder, wenn auch wahrscheinlich erst nach einigen Wochen Reha. Aber seine Schwester sei bei der Einlieferung seltsam stark unterkühlt gewesen. Auch was Rike zum Unfallhergang erzählt hatte, wirke „durchaus neurologisch auffällig, Herr Kollege“, obwohl der Helm wohl Schlimmeres verhindert habe. „Pupillen waren aber eng und isokor. Lichtreaktion direkt und konsensuell prompt. CT haben wir vorsorglich auch gemacht, ohne Befund. Wir müssen das wohl einfach weiter beobachten.“ Klang etwas wie in der Autowerkstatt. Dann musste die Kollegin auch schon weiter, noch bevor Paul entscheiden konnte, ob er Rikes Diagnose vorsorglich erwähnen sollte.

Bald darauf hatte ihm seine Schwester noch nicht wieder ganz wach schon 23 der dringendsten Care-Arbeit-to-dos runtergerattert: wer welches Frühstück bekam und unbedingt nur dieses und wann wer welche Medikamente, Montag Kuscheltier-Tag in Julias Kita und Niklas‘ Latein-Arbeit, Lenis Geburtstagsnachfeier nächste Woche, KJP-Termin, dies, das.

Wie seine Schwester diese Mental Load stemmte, war ihm ein Rätsel. Leider galt das aber auch für ihre Erklärung zum Unfall: „Ich weiß es doch auch nicht, Paul. Da tauchte auf einmal dieser Schneemann hinter der Kurve auf. Ich war wohl kurz abgelenkt, bin dann gegen den Baumstumpf, über den Lenker, in den Schneemann rein. Dann war es dunkel.“ Seltsam. Ein Schneemann? Ob das noch an der Vollnarkose lag? An der Unterkühlung? Doch eine Gehirnerschütterung? Der letzte Schnee in Seligenburg war lange her. Das hatte ihm einer der Pfleger bestätigt. Ein Glück eigentlich, denn natürlich hatte er seine Winterreifen („Von O bis O!“ sagten sie in der Werkstatt immer: „Oktober bis Ostern!“) noch immer nicht drauf.

Jetzt trotzdem Gas geben, die Gedanken ans Krankenhaus, die Praxis zu Hause und an die nächsten Wochen parken und erstmal nur auf die nächsten Kilometer konzentrieren. „Bitte wenden!“ insistierte die Navi-Stimme ein letztes Mal. Und na klar, da ging sie schon an, die warnende Motorkontroll-Leuchte und die Anzeige „Motor kontrollieren lassen!“. Auf manches war im Leben eben doch Verlass.
